### PR TITLE
Add label to text property  #9.

### LINKED ISSUE #9: fcitx5-skk Dictionary Manager 's Button is not displayed correctly.
fcitx5-skk Dictionary Manager 's Button is not displayed correctly.

Please tell me how to fix.

My envrionment:
- Debian 11(amd64)
- i3wm
- fcitx5 5.0.5-1/ fcitx5-skk 5.0.4-1 (from apt)

### PR DESCRIPTION
**Pull request by rkarsnk**
I tried to fix #9 .

### CODE REVIEW

**Comment by wengxt** [comment]
Please don't remove the icon. Tool button should automatically fallbcak to text if icon is not available.

**Comment by rkarsnk** [comment]
Thank you for review. I Fixed a PR.

**Comment by rkarsnk** [comment]
Thank you for review. I Fixed a PR.

**Comment by wengxt** [comment]
Thanks!

Though the translation won't be applied because the synchronization is one way from transifex to repo. If you want you can also help on : https://www.transifex.com/fcitx/

**Comment by rkarsnk** [comment]
Thanks for merge!

**Pull request merged**
